config/routes.rb
Undoer::Application.routes.draw do

  devise_for :users
  root to: 'posts#index'

  get '/posts/history', to: 'posts#history', as: :posts_history
  post '/posts/:id/undo', to: 'posts#undo', as: :undo

  resources :posts

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  body       :text
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  has_paper_trail
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def info_for_paper_trail
    # Save additional info
    { ip: request.remote_ip }
  end

  def user_for_paper_trail
    # Save the user responsible for the action
    user_signed_in? ? current_user.id : 'Guest'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :history, :show]

  def history
    @versions = PaperTrail::Version.order('created_at DESC').paginate(page: params[:page], per_page: 35)
  end

  def undo
    @post_version = PaperTrail::Version.find_by_id(params[:id])

    begin
      if @post_version.reify
        @post_version.reify.save
      else
        # For undoing the create action
        @post_version.item.destroy
      end
      flash[:success] = "Undid that! #{make_redo_link}"
    rescue
      flash[:alert] = "Failed undoing the action..."
    ensure
      redirect_to root_path
    end
  end

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = "Post was created! #{make_undo_link}"
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def show
    @post = Post.find_by_id(params[:id])
  end

  def edit
    @post = Post.find_by_id(params[:id])
  end

  def update
    @post = Post.find_by_id(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = "Post was updated! #{make_undo_link}"
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    if @post.destroy
      flash[:success] = "Post was destroyed! #{make_undo_link}"
    else
      flash[:alert] = 'Error while desroying the post!'
    end
    redirect_to root_url
  end

  private

  def post_params
    params.require(:post).permit(:body, :title)
  end

  def make_undo_link
    view_context.link_to 'Undo that plz!', undo_path(@post.versions.last), method: :post
  end

  def make_redo_link
    params[:redo] == "true" ? link = "Undo that plz!" : link = "Redo that plz!"
    view_context.link_to link, undo_path(@post_version.next, redo: !params[:redo]), method: :post
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Undoer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Undoer', root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'History', posts_history_path %></li>
      </ul>

      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        </ul>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= value.html_safe %>
    </div>
  <% end %>
</div>

<div class="container">
  <%= yield %>
</div>

<div id="footer">
  <div class="container">
    <p class="text-muted">Created by <a href="http://radiant-wind.com" target="_blank">Radiant Wind</a></p>
  </div>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= render 'shared/errors', object: @post %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <h1>Edit post <%= @post.title %></h1>

  <%= render 'form' %>
</div>

app/views/posts/history.html.erb
<div class="container">
  <h1>History</h1>

  <ul>
    <% @versions.each do |version| %>
      <li>
        <%= l(version.created_at, format: "%-d.%m.%Y %H:%M:%S %Z") %><br/>
        Event ID: <%= version.id %><br/>
        <b>Remote address:</b> filtered out<br/>
        <b>Target:</b> <%= version.item_type %>
        <small>(id: <%= version.item_id %>)</small>; <b>action</b> <%= version.event %>;<br/>

        <b>User:</b>
        <% if version.whodunnit && version.whodunnit != 'Guest' %>
          <% user = User.find_by_id(version.whodunnit) %>
          <% if user %>
            <%= user.email %>
            (last seen at <%= l(user.last_sign_in_at, format: "%-d.%m.%Y %H:%M:%S") %>)
          <% end %>
        <% else %>
          Guest
        <% end %>

        <div>
          Changeset:
          <pre><%= version.changeset %></pre>
        </div>
        <div>
          More info:
          <pre><%= version.object %></pre>
        </div>
      </li>
    <% end %>
  </ul>

  <%= will_paginate @versions %>
</div>

app/views/posts/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Welcome to the blog!</h1>
    <% if user_signed_in? %>
      <p>Click the button below to add your post.</p>
      <p><%= link_to "Add post", new_post_path, class: 'btn btn-primary btn-lg' %></p>
    <% else %>
      <p>Click the button below to sign up to be able to add posts.</p>
      <p><%= link_to "Sign up", new_user_registration_path, class: 'btn btn-primary btn-lg' %></p>
    <% end %>
  </div>
</div>

<div class="container">
  <table class="table table-striped">
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Actions</th>
    </tr>

    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post_path(post) %></td>
        <td><%= truncate(post.body, length: 200) %></td>
        <td><%= link_to 'Edit', edit_post_path(post), class: 'btn btn-primary' %>
          <%= link_to 'Destroy', post_path(post), class: 'btn btn-danger', method: :delete,
                      confirm: 'Are you sure?' %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1>New post</h1>

  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <h1><%= @post.title %></h1>

  <p><%= @post.body %></p>

  <div>
    <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-primary' %>
    <%= link_to 'Destroy', post_path(@post), class: 'btn btn-danger', method: :delete,
                confirm: 'Are you sure?' %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title">The following errors were found while submitting the form:</h3>
    </div>

    <div class="panel-body">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>